
[font]
normal = { family = "FiraCodeNerdFont", style = "Regular" }
bold = { family = "FiraCodeNerdFont", style = "Bold" }
italic = { family = "FiraCodeNerdFont", style = "Italic" }

size = 12.0

[general]
import = [
    "alacritty-theme/themes/catppuccin_mocha.toml"
]

