[window]
dynamic_padding = true
opacity = 0.7
blur = true


[font]
normal = { family = "FiraCodeNerdFont", style = "Regular" }
bold = { family = "FiraCodeNerdFont", style = "Bold" }
italic = { family = "FiraCodeNerdFont", style = "Italic" }

size = 12.0

[general]
import = [
    "themes/one_dark.toml"
]

